EXE := pinpoint

all: mtg-2016-11-07

mtg-2016-11-07:
	$(EXE) --output=mtg-2016-11-07.pdf mtg-2016-11-07.pin

simple:
	(cd examples; $(EXE) --output=simple-demo.pdf simple-demo.pin)

complex:
	(cd examples; $(EXE) --output=introduction.pdf introduction.pin)
